databases:
  - name: database
    databaseName: database_zq36
    user: database_zq36_user

services:
  - type: web
    name: depth_and_core
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: database
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false